services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: echo "Echo from main Docker Compose"
    volumes:
      - .:/app

  db:
    image: alpine:3.20
    command: sleep infinity

  sidecar1:
    image: alpine:3.20
    command: sleep infinity

  sidecar2:
    image: alpine:3.20
    command: sleep infinity

